AWSTemplateFormatVersion: "2010-09-09"
Description: "(SO0164) AWS Content Localization - Deploys the AWS Content Localization Application over an existing Media Insights Engine stack."

Parameters:
  MieStackName:
    Description: Name of the Media Insights Engine framework stack
    Type: String
  AdminEmail:
    Description: Email address of the Content Analysis Administrator
    Type: String
  ElasticSearchNodeSize:
    Description: "The node type to be provisioned for the Elasticsearch cluster"
    Type: String
    Default: "t3.small.elasticsearch"
    AllowedValues:
      - "t3.small.elasticsearch"
      - "m4.large.elasticsearch"
      - "m4.xlarge.elasticsearch"
      - "c4.large.elasticsearch"
      - "c4.xlarge.elasticsearch"
      - "r4.large.elasticsearch"
      - "r4.xlarge.elasticsearch"

Mappings:
  Application:
    SourceCode:
      GlobalS3Bucket: "%%GLOBAL_BUCKET_NAME%%"
      TemplateKeyPrefix: "aws-content-localization/%%VERSION%%"
      RegionalS3Bucket: "%%REGIONAL_BUCKET_NAME%%"
      CodeKeyPrefix: "aws-content-localization/%%VERSION%%"
      Version: "%%VERSION%%"

Resources:

  # Deploy Elasticsearch
  ElasticsearchStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - Application
            - SourceCode
            - GlobalS3Bucket
          - ".s3.amazonaws.com/"
          - !FindInMap
            - Application
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-localization-elasticsearch.template"
      Parameters:
        AnalyticsStreamArn:
          Fn::ImportValue:
            !Sub "${MieStackName}:AnalyticsStreamArn"
        MieDataplaneBucket:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneBucket"
        NodeType: !Ref ElasticSearchNodeSize

  # Deploy Auth stack

  AuthStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - Application
            - SourceCode
            - GlobalS3Bucket
          - ".s3.amazonaws.com/"
          - !FindInMap
            - Application
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-localization-auth.template"
      Parameters:
        AdminEmail: !Ref AdminEmail
        WorkflowApiId:
          Fn::ImportValue:
            !Sub "${MieStackName}:WorkflowApiId"
        DataplaneApiId:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneApiId"
        ElasticDomainArn: !GetAtt ElasticsearchStack.Outputs.DomainArn
        DataplaneBucket:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneBucket"
        ParentStackName: !Ref AWS::StackId

  # Deploy Video Workflow
  VideoWorkflow:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - Application
            - SourceCode
            - GlobalS3Bucket
          - ".s3.amazonaws.com/"
          - !FindInMap
            - Application
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-localization-video-workflow.template"
      Parameters:
        WorkflowCustomResourceArn:
          Fn::ImportValue:
            !Sub "${MieStackName}:WorkflowCustomResourceArn"
        OperatorLibraryStack:
          Fn::ImportValue:
            !Sub "${MieStackName}:OperatorLibraryStack"

  WebStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: !Join
        - ""
        - - "https://"
          - !FindInMap
            - Application
            - SourceCode
            - GlobalS3Bucket
          - ".s3.amazonaws.com/"
          - !FindInMap
            - Application
            - SourceCode
            - TemplateKeyPrefix
          - "/aws-content-localization-web.template"
      Parameters:
        DataplaneEndpoint:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneApiEndpoint"
        WorkflowEndpoint:
          Fn::ImportValue:
            !Sub "${MieStackName}:WorkflowApiEndpoint"
        ElasticEndpoint: !GetAtt ElasticsearchStack.Outputs.ElasticEndpoint
        DataplaneBucket:
          Fn::ImportValue:
            !Sub "${MieStackName}:DataplaneBucket"
        UserPoolId: !GetAtt AuthStack.Outputs.UserPoolId
        IdentityPoolId: !GetAtt AuthStack.Outputs.IdentityPoolId
        PoolClientId: !GetAtt AuthStack.Outputs.UserPoolClientId

Outputs:
  ContentLocalizationSolution:
    Value: !GetAtt WebStack.Outputs.CloudfrontUrl
  ElasticEndpoint:
    Value: !GetAtt ElasticsearchStack.Outputs.ElasticEndpoint
  UserPoolId:
    Value: !GetAtt AuthStack.Outputs.UserPoolId
  IdentityPoolId:
    Value: !GetAtt AuthStack.Outputs.IdentityPoolId
  UserPoolClientId:
    Value: !GetAtt AuthStack.Outputs.UserPoolClientId
