name: iantest

on:
  workflow_dispatch:

jobs:

  iantest:
    runs-on: ubuntu-latest
    env:
      MIE_REGION: 'us-west-2'
      TEMPLATE: 'https://solutions-reference:s3:amazonaws:com/content-localization-on-aws/latest/content-localization-on-aws.template'
    steps:
      - name: Initialize build AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
 
      - name: Get latest release number
        run: |
          echo "LATEST_VERSION=$(wget -q -O- $TEMPLATE | grep SolutionVersion | cut -f 2 -d '"')" >> $GITHUB_ENV
          echo $LATEST_VERSION
      
      - name: Check out release branch
        uses: actions/checkout@v2.3.4
        with:
          ref: release/$LATEST_VERSION

