name: iantest

on:
  workflow_dispatch:

jobs:

  iantest:
    runs-on: ubuntu-latest
    env:
      MIE_REGION: 'us-west-2'
    steps:
      - name: Get latest release number
        run: |
          aws cloudformation get-template --stack-name clsol --region us-west-2 --query 'TemplateBody' | grep -o 'SolutionVersion: \\"v\d*.\d*.\d*\\"' 
          
          aws cloudformation get-template --stack-name clsol --region us-west-2 --query 'TemplateBody' | grep -o 'SolutionVersion: \\"v\d*.\d*.\d*\\"' | tr -d '\\' | cut -f 2 -d '"'

          echo "LATEST_VERSION=$(aws cloudformation get-template --stack-name clsol --region us-west-2 --query 'TemplateBody' | grep -o 'SolutionVersion: \\"v\d*.\d*.\d*\\"' | tr -d '\' | cut -f 2 -d '"')" >> $GITHUB_ENV
      
      - name: Check out release branch
        uses: actions/checkout@v2.3.4
        with:
          ref: release/$LATEST_VERSION

